---

- hosts: all
  tasks:

  - name: Install h.264 dependancies
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - gstreamer1-vaapi
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugin-openh264
      - mozilla-openh264
      - ffmpeg-libs
    become: true
