---

- hosts: all
  tasks:

  - name: Add EPEL repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    become: true

  - name: Add openh264 repository
    yum_repository:
      name: fedora-cisco-openh264
      description: Fedora $releasever openh264 (From Cisco) - $basearch
      baseurl: https://codecs.fedoraproject.org/openh264/$releasever/$basearch/
      gpgcheck : yes
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch

      enabled: yes
    become: true

  - name: Install h.264 dependancies
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - gstreamer1-libav
      - gstreamer1-vaapi
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-ugly
      - gstreamer1-plugin-openh264
      - mozilla-openh264
      - chromium-libs-media-freeworld
    become: true
