---

- import_playbook: docker.yml

- hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Pull the latest official jenkins docker image
    docker_image:
      name: "jenkins/jenkins:lts"
      source: pull

  - name: Create a volume for jenkins data
    docker_volume:
      name: jenkins_home

  - name: Create a container from the jenkins docker image
    docker_container:
      name: "jenkins-server"
      image: "jenkins/jenkins:lts"
      ports:
          - "8080:8080"
          - "50000:50000"
      volumes:
          - "jenkins_home:/var/jenkins_home"
      state: started
      restart_policy: unless-stopped
      recreate: yes