---

- hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Turn off host key checking
    ini_file:
      path: ~/.ansible.cfg
      section: defaults
      option: host_key_checking
      value: False

  - name: Set inventory file path
    ini_file:
      path: ~/.ansible.cfg
      section: defaults
      option: inventory
      value: ~/.ansible_hosts

  - name: Initalise inventory file
    copy:
      content: |
               [self]
               localhost              ansible_connection=local

               [all:vars]
               ansible_python_interpreter=/usr/bin/python3
      dest: ~/.ansible_hosts
      force: no
