---

- hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Install Ansible dependancies
    package:
      name: libselinux-python
      state: latest
    become: true

  - name: Turn off host key checking
    ini_file:
      path: ~/.ansible.cfg
      section: defaults
      option: host_key_checking
      value: False

  - name: Set inventory file path
    ini_file:
      path: ~/.ansible.cfg
      section: defaults
      option: inventory
      value: ~/.ansible_hosts

  - name: Initalise inventory file
    copy:
      content: ""
      dest: ~/.ansible_hosts
      force: no
