---

- hosts: all
  tasks:

  - name: Install Ansible dependancies
    package:
      name: python3-firewall
      state: latest
    become: true

  - name: Install mDNS software
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - avahi
      - avahi-tools
      - nss-mdns
    become: true
    notify: Restart Avahi

  - name: Open firewall ports for mDNS and ssh
    firewalld:
      service: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    with_items:
      - ssh
      - mdns
    become: true

  - name: Enable and Start Avahi
    service:
      name: avahi-daemon
      enabled: yes
      state: started
    become: true

  handlers:
  - name: Restart Avahi
    service:
      name: avahi-daemon
      state: restarted
    become: true
