---

- hosts: all
  tasks:

  - name: Add openh264 repository
    yum_repository:
      name: fedora-cisco-openh264
      description: Fedora $releasever openh264 (From Cisco) - $basearch
      baseurl: https://codecs.fedoraproject.org/openh264/$releasever/$basearch/
      gpgcheck : yes
      gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch

      enabled: yes
    become: true
