---

- hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Allow "wheel" group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: "^%wheel"
      line: "%wheel ALL=(ALL) NOPASSWD: ALL"
      validate: "visudo -cf %s"
    become: true
