---

- hosts: all
  tasks:

  - name: Update OS
    dnf:
      name: '*'
      state: latest
    become: true
    notify: Reboot

  handlers:
    - name: Reboot
      shell: sleep 2 && /sbin/shutdown -r now "System packages upgraded"
      become: true
