---

- hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Checking Maven Local Repository
    find:
      paths: ~/.m2/
      age: 10d
    register: files_to_delete

  - name: Cleaning Maven local repository
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"

  - name: Checking Gradle build cache
    find:
      paths: ~/.gradle/caches/
      age: 10d
    register: files_to_delete

  - name: Cleaning Gradle build cache
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
