---

- hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Clean Maven Local
    find:
      paths: ~/.m2/
      age: 10d
    register: files_to_delete

  - name: Ansible remove files older than a date example
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"